# DIGI118 Oppgave 1a
---

**Lag først en kopi av denne notatboken ved hjelp av knappen øverst til høyre i dette vinduet. 
Nå er du klar til å kode i din egen versjon av denne notatboken. 

Bruk `bergen_sampled.csv` fra Bergen Bike Share-datasettet. Dette har 5000 datapunkter, som er det maksimale antallet punkter som Vega-Altair kan jobbe med (uten å legge til utvidelser for dette biblioteket).

In [1]:
# Import libraries
import pandas as pd
import altair as alt
# YOUR CODE HERE

In [4]:
# Read in data
# YOUR CODE HERE
bike = pd.read_csv("bergen-bike-sharing-dataset-2023/bergen_sampled.csv")
# Preview the dataframe
# YOUR CODE HERE
bike.head()

,start_time,end_time,duration,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,precipitation,temperature,wind_speed,weather,sunshine,season,is_holiday,is_weekend
0,2023-05-01 10:00:00,2023-05-01 10:00:00,384,639,Frydenbø Marina,60.384467,5.310008,819,Thormøhlens gate,60.383162,5.324053,0.0,6.7,5.3,3,60,0,True,False
1,2023-05-01 11:00:00,2023-05-01 11:00:00,310,49,Studentsenteret UiB,60.387198,5.322980,151,Småstrandgaten,60.393098,5.327023,0.0,7.8,5.6,3,57,0,True,False
2,2023-05-01 12:00:00,2023-05-01 12:00:00,99,3,Grieghallen,60.388197,5.328564,804,Stenersen,60.390174,5.324792,0.0,8.2,7.5,3,25,0,True,False
3,2023-05-01 12:00:00,2023-05-01 13:00:00,4359,791,Busstasjonen 4 Sør,60.387059,5.335634,214,Nygårdsporten,60.383934,5.333450,0.0,8.2,7.5,3,25,0,True,False
4,2023-05-01 13:00:00,2023-05-01 13:00:00,1278,806,Dreggsallmenningen Sør,60.397709,5.322001,2336,Møllestranden,60.380044,5.350824,0.0,8.1,8.2,4,38,0,True,False

In [7]:
bike.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   start_time               5000 non-null   object
 1   end_time                 5000 non-null   object
 2   duration                 5000 non-null   int64
 3   start_station_id         5000 non-null   int64
 4   start_station_name       5000 non-null   object
 5   start_station_latitude   5000 non-null   float64
 6   start_station_longitude  5000 non-null   float64
 7   end_station_id           5000 non-null   int64
 8   end_station_name         5000 non-null   object
 9   end_station_latitude     5000 non-null   float64
 10  end_station_longitude    5000 non-null   float64
 11  precipitation            5000 non-null   float64
 12  temperature              5000 non-null   float64
 13  wind_speed               5000 non-null   float64
 14  weather                  5000 non-null   int64
 15  sunshine                 5000 non-null   int64
 16  season                   5000 non-null   int64
 17  is_holiday               5000 non-null   bool
 18  is_weekend               5000 non-null   bool
dtypes: bool(2), float64(7), int64(6), object(4)
memory usage: 674.0+ KB

In [6]:
# Specify chart title and description
# YOUR CODE HERE
chart_title = alt.Title(
       "Bike sharing in Bergen",
       subtitle="Something something bike sharing subtitle"
)
# Draw a histogram with a chart title and description. Annotate the data type of each field.
# YOUR CODE HERE
bike = alt.Chart(start_time, title=chart_title).mark_line().encode(
    alt.X("Time:T"),
    alt.Y("Air temperature:Q")
)
# Display chart
# YOUR CODE HERE
bike

NameError: name 'start_time' is not defined

In [ ]:
# Save the chart to Kaggle's Output working folder in order to download it.
# YOUR CODE HERE

---
# Ressurser
- [DIGI118 Modul 0: Heisann, Python!](https://www.kaggle.com/code/lauragarrison/digi118-h24-modul-0-heisann-python) 
- [DIGI118 Module 0: Heisann, Pandas!](https://www.kaggle.com/code/lauragarrison/digi118-h24-modul-0-heisann-pandas)
- [DIGI118 Modul 1: Heisann, Altair!](https://www.kaggle.com/code/lauragarrison/digi118-modul-1-heisann-altair)
- Pandas-dokumentasjon: https://pandas.pydata.org/docs/reference/index.html
- Altair-dokumentasjon: https://altair-viz.github.io/user_guide/api.html
- Eksempler på Altair-diagrammer, inkludert histogrammer: https://altair-viz.github.io/gallery